# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e43b4848120dd8fd39b82a800a680cd14354c277e3675d0ec10fc481ba0f2a60f965d19de63dcac1c455007d6a5b9639340537fbd759e60c3b25771ea057f4d

test:
  secret_key_base: 72937955176635675ba0e3ae2b220a0d6b4408aa5a5e261cc2f250a6bc243d8ef6f168c7bf2b3538287c602655274627ee993544408aee32618f064c7df67312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
